添加禁用函数检查的 lint
MiaoSiLa/golangci-lint pull request #1
Opened 2020-11-02 09:44 UTC by SeigeC

添加禁用函数检查的 lint

2020-11-10 07:08 UTC, icylight commented on pkg/golinters/bannedfunc.go
> +	).WithContextSetter(func(lintCtx *linter.Context) {
不要写成匿名函数

2020-11-10 07:18 UTC, icylight commented on pkg/golinters/bannedfunc.go
> +	wd, _ := os.Getwd()
这里不需要空行吧

2020-11-10 07:18 UTC, icylight commented on pkg/golinters/bannedfunc.go
> +		panic(err)
这里为什么要 panic?

2020-11-10 07:18 UTC, icylight commented on pkg/golinters/bannedfunc.go
> +		panic(err)
这里也一样，为什么要 panic

2020-11-10 07:19 UTC, icylight commented on pkg/golinters/bannedfunc.go
> +	Analyzer.Run = func(pass *analysis.Pass) (interface{}, error) {
这里也不要用匿名函数

2020-11-10 07:20 UTC, icylight commented on pkg/golinters/bannedfunc.go
> +	configMap := make(map[string]map[string]string)
这个加下注释，我这个 map 的三个 string 分别代表了什么

2020-11-10 07:25 UTC, icylight commented
更新一些配置的示例

2020-11-10 07:35 UTC, SeigeC commented on pkg/golinters/bannedfunc.go
> +		panic(err)
读取配置文件失败后就没有必要执行了，painc 后 golangci-lint 会拦截。不会影响其他 lint 的执行

2020-11-10 08:28 UTC, icylight commented on pkg/golinters/bannedfunc.go
> +	Values map[string]map[string]string `yaml:"values"`
这里三个 string 加下注释

2020-11-10 08:35 UTC, icylight commented on pkg/golinters/bannedfunc.go
> +	"gopkg.in/yaml.v3"
这个换成 golangci-lint 引入的 yaml 包版本

2020-11-10 10:26 UTC, icylight commented on pkg/golinters/bannedfunc.go
> +func astFunc(pass *analysis.Pass, useMap map[string]map[string]string) func(node ast.Node) bool {
`useMap` 改下

2020-11-10 10:29 UTC, icylight commented on pkg/golinters/bannedfunc.go
> +		strs := strings.Split(k, ")")
这里用 `).` 分割

2020-11-10 10:30 UTC, icylight commented on pkg/golinters/bannedfunc.go
> +		var pkg, name = strs[0][1:], strs[1][1:]
这里 pkg 会 panic 的

2020-11-10 10:31 UTC, icylight commented on pkg/golinters/bannedfunc.go
> +		configMap[pkg] = m
这里读取出来除非 m == nil 应该其他情况不需要赋值

2020-11-10 10:39 UTC, icylight commented on pkg/golinters/bannedfunc.go
> +package golinters
这个文件需要补充单元测试

2020-11-10 12:05 UTC, icylight commented on pkg/golinters/bannedfunc.go
> +		return true
这里有 return false 的情况吗？

2020-11-10 12:06 UTC, icylight commented on pkg/golinters/bannedfunc.go
> +// example:
例子再改下，现在给的不太合理

2020-11-10 12:15 UTC, icylight commented on pkg/golinters/bannedfunc_test.go
> +	"testing"
这里错了

2020-11-10 12:15 UTC, icylight commented on pkg/golinters/bannedfunc_test.go
> +	var b = []byte("linters-settings:\n  bannedfunc:\n    (time).Now: \"不能使用 time.Now() 请使用 MiaoSiLa/missevan-go/util 下 TimeNow()\"\n    (github.com/Missevan/missevan-go/util/time).TimeNow: \"xxxx\"")
这个名字改下

2020-11-10 12:16 UTC, icylight commented on pkg/golinters/bannedfunc_test.go
> +func Test_configToConfigMap(t *testing.T) {
同上

2020-11-10 12:16 UTC, icylight commented on pkg/golinters/bannedfunc_test.go
> +	m["(time).Now"] = "不能使用 time.Now() 请使用 MiaoSiLa/missevan-go/util 下 TimeNow()"
key 至少要匹配到这些情况
```
().
).
```

2020-11-11 07:50 UTC, icylight commented on pkg/golinters/bannedfunc_test.go
> +	m[")."] = ").情况"
这两个的错误文案遵循中英文规范

2020-11-11 07:54 UTC, icylight commented on pkg/golinters/bannedfunc_test.go
> +	})
这里只有 decodeFile 这一步需要放在 NotPanics 中，其他不需要吧

2020-11-11 07:54 UTC, icylight commented on pkg/golinters/bannedfunc_test.go
> +	m[")."] = ").情况"
直接
```golang
m := map[string]string{
}
```

2020-11-11 08:29 UTC, icylight commented on pkg/golinters/bannedfunc_test.go
> +	var b = []byte("linters-settings:\n  bannedfunc:\n    (time).Now: \"不能使用 time.Now() 请使用 MiaoSiLa/missevan-go/util 下 TimeNow()\"\n    (github.com/Missevan/missevan-go/util/time).TimeNow: \"xxxx\"")
这里也改一下

2020-11-11 09:04 UTC, tengattack commented on .golangci.example.yml
> +    (time).Now: "不能使用 time.Now() 请使用 MiaoSiLa/missevan-go/util 下 TimeNow()"
`不能使用 time.Now()` 后面加个逗号

2020-11-11 09:08 UTC, icylight commented on pkg/golinters/bannedfunc_test.go
> +	b := []byte("linters-settings:\n  bannedfunc:\n    (time)." + "Now: \"xxxx\"\n    (github.com/Missevan/missevan-go/util/time).TimeNow: \"xxxx\"")
你中间的 `+` 是做什么用啊

2020-11-11 09:08 UTC, icylight commented on pkg/golinters/bannedfunc_test.go
> +	assert.Equal("不能使用 time.Now() 请使用 MiaoSiLa/missevan-go/util 下 TimeNow()", val)
这里非空的话，直接 equal 就行吧？

2020-11-11 09:09 UTC, icylight commented on pkg/golinters/bannedfunc_test.go
> +	assert.Equal("xxxx", val)
同上

2020-11-11 09:11 UTC, icylight commented on pkg/golinters/bannedfunc_test.go
> +	assert.Len(setting, 2)
这里放在 setting 获取出来之后判断，并且换成 require

2020-11-11 12:01 UTC, icylight commented on pkg/golinters/bannedfunc.go
> +			useMap[item.Name()] = make(map[string]string)
这里是不是写错了

2020-11-11 12:02 UTC, icylight commented on pkg/golinters/bannedfunc.go
> +func astFunc(pass *analysis.Pass, usedMap map[string]map[string]string) func(node ast.Node) bool {
这个能不能测试下？

2020-11-12 09:26 UTC, icylight commented on pkg/golinters/bannedfunc.go
> +		if !ok {
这里用 m == nil 代替

2020-11-12 10:52 UTC, icylight commented on pkg/golinters/bannedfunc_test.go
> +func Test_astFunc(t *testing.T) {
函数名改下

2020-11-12 10:52 UTC, icylight commented on pkg/golinters/bannedfunc_test.go
> +	var testStr string
变量定义尽可能的靠近使用的地方

2020-11-12 10:52 UTC, icylight commented on pkg/golinters/bannedfunc_test.go
> +	m := map[string]map[string]string{
同上

2020-11-12 10:57 UTC, SeigeC commented on pkg/golinters/bannedfunc_test.go
> +	var testStr string
![image](https://user-images.githubusercontent.com/39756973/98931325-d355f200-2518-11eb-98b8-96f8a71807b4.png)
这里会用到这个变量 所以不能往下移

2020-11-12 12:29 UTC, icylight approved these changes

2020-11-12 13:12 UTC, tengattack commented
解决下 checks 问题

2020-11-12 13:13 UTC, tengattack commented on pkg/golinters/bannedfunc_test.go
> +	b := []byte("linters-settings:\n  bannedfunc:\n    (time).Now: \"xxxx\"\n    (github.com/Missevan/missevan-go/util).TimeNow: \"xxxx\"")
可以用反单引号写成多行的形式 + strings.TrimSpace

2020-11-12 14:41 UTC, tengattack approved these changes

2020-11-12 14:51 UTC, icylight approved these changes

2020-11-12 16:23 UTC, tengattack commented on pkg/golinters/bannedfunc.go
> +	"github.com/golangci/golangci-lint/pkg/golinters/goanalysis"
我好像知道了，这个得放到最下面一组的 import 里，就是单独分开这个 local-prefixes 的

2020-11-12 16:29 UTC, tengattack commented on pkg/golinters/bannedfunc.go
> +	Name:     "time",
这里 name 和下面 doc 好像都可以更新下？

2020-11-12 16:30 UTC, tengattack reviewed
有那种能跑完完整测试，然后看到有一些 bannedfunc issue 的测试吗？

2020-11-12 16:31 UTC, tengattack requested changes
。

2020-11-13 03:57 UTC, tengattack reviewed
可以加个示例的 .go 文件到 testdata 里去完整模拟这个 go 文件的测试？

2020-11-13 04:01 UTC, SeigeC commented
> 可以加个示例的 .go 文件到 testdata 里去完整模拟这个 go 文件的测试？

目前网上的博客都是在运行时指定文件的路径，我在找有没有能够在代码里指定配置的方法

2020-11-13 09:34 UTC, icylight commented on pkg/golinters/bannedfunc_test.go
> +	want := []string{
移到下面用的地方定义

2020-11-13 10:44 UTC, icylight approved these changes

2020-11-13 13:29 UTC, tengattack commented on pkg/golinters/bannedfunc_test.go
> +	// Notice: 因为配准的初始化函数将 GOPATH 设置为当前目录
NOTICE 这边都要大写

2020-11-13 13:29 UTC, tengattack commented on pkg/golinters/bannedfunc_test.go
> +	m := map[string]map[string]string{
用配置的描述来测文件

2020-11-13 14:22 UTC, tengattack commented on pkg/golinters/bannedfunc_test.go
> +	// NOTICE: 因为配准的初始化函数将 GOPATH 设置为当前目录
配准是啥意思

2020-11-16 04:05 UTC, icylight approved these changes

2020-11-16 04:15 UTC, SeigeC commented on pkg/golinters/bannedfunc_test.go
> +	m := map[string]map[string]string{
添加完了

2020-11-16 04:31 UTC, tengattack approved these changes

2020-11-16 04:32 UTC, merged